<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc53194826d51c1d00032d1e2a20dcefc
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SentimentAnalysis\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SentimentAnalysis\\' => 
        array (
            0 => __DIR__ . '/..' . '/risan/sentiment-analysis/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc53194826d51c1d00032d1e2a20dcefc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc53194826d51c1d00032d1e2a20dcefc::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
